branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - lint-pr
          - chat-api
          - chat-cli
          - chat-server
      required_linear_history: true