version: '3.6'
services:
  chat-api:
    image: pidgeon-post/chat-api
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${API_POSTGRES_PASSWORD}@db:5432/${API_POSTGRES_DB}?schema=public}"
    build:
      context: ./chat-api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db 
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${API_POSTGRES_DB}
      - POSTGRES_PASSWORD=${API_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local