# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

# on:
#   pull_request:
#     types:
#       - opened
#       - edited
#       - synchronize
#     branches:
#       - main
#   push:
#     branches:
#       - main

# name: Chat API

# jobs:
#   check:
#     name: Check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v2

#       - name: Install stable toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true

#       - name: Run cargo check
#         uses: actions-rs/cargo@v1
#         with:
#           command: check
#           args: --manifest-path chat-api/Cargo.toml

#   test:
#     name: Test Suite
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v2

#       - name: Install stable toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true

#       - name: Run cargo test
#         uses: actions-rs/cargo@v1
#         with:
#           command: test
#           args: --manifest-path chat-api/Cargo.toml

#   lints:
#     name: Lints
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v2

#       - name: Install stable toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true
#           components: rustfmt, clippy

<<<<<<< HEAD
      # - name: Run cargo fmt
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fmt
      #     args: --manifest-path chat-api/Cargo.toml --all -- --check
=======
<<<<<<< HEAD
#       - name: Run cargo fmt
#         uses: actions-rs/cargo@v1
#         with:
#           command: fmt
#           args: --manifest-path chat-server/Cargo.toml --all -- --check
=======
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path chat-api/Cargo.toml --all -- --check
>>>>>>> d2678ff (fix chat-api lint and run cargo fmt)
>>>>>>> 0acf2c5 (fix chat-api lint and run cargo fmt)

#       - name: Run cargo clippy
#         uses: actions-rs/cargo@v1
#         with:
#           command: clippy
#           args: --manifest-path chat-api/Cargo.toml -- -D warnings 